sudo: required

language: node_js
node_js:
  - "lts/*"
services:
  - docker

before_install:
  - mv Makefile.config.template Makefile.config
  - make one-click-deploy-debug

script:
  - make docker-node-debug-test
