version: '3'
services:
  service:
    container_name: nb-service-ctn    
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
    image: nb-service:reply2future
    env_file:
      - ./docker-compose.env
    volumes:
      - ./db:/db
    ports:
      - 3000:3000
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "10"  
